### ISSUE TITLE
Fixing Enchanted Items

### ISSUE THREAD

**Issue by XHazardX420** [Derpific/Fix#3]
I tried fixing a pickaxe with eff 1 and it didn't work and I have the newest update the error was 
CRITICAL> Unhandled exception executing command 'fix hand' in fix: Class Derpific\Commands\Enchantment not found
2017-06-19 [Tesseract] [21:50:53] CRITICAL> ClassNotFoundException: "Class Derpific\Commands\Enchantment not found" (EXCEPTION) in "/src/spl

**Comment by Derpific** [comment]
Are you using the latest one?

**Comment by Derpific** [comment]
If not, I think I forgot to import a Enchantment class

**Comment by XHazardX420** [comment]
Yes im using the latest one

**Comment by Derpific** [comment]
I updated. It should fix now, also updated to ALPHA6, removed unused statements. Enjoy!
